site_name: "Adele Magic System" 
site_url: https://adeleprism.github.io/Magic-System
theme:
    name: 'material'
    palette:
      scheme: slate
      primary: deep purple
      accent: blue
    features: 
      - navigation.path
      - navigation.footer
      - navigation.indexes
markdown_extensions:
  - toc:
      toc_depth: 0

nav:
  - index.md
  - Magic :
    - Basics of Magic :
      - Magic/Basics of Magic/ğŸ§  Emotions.md
      - Magic/Basics of Magic/ğŸ§™â€â™€ï¸ Affinity.md
      - Magic/Basics of Magic/âœ¨ï¸ Souls of Magic.md
      - Magic/Basics of Magic/ğŸ”£ Links.md
      - Magic/Basics of Magic/ğŸ“œ Spells.md
    - Elements :
      - Magic/Elements/âš¡ï¸ Shock.md
      - Magic/Elements/ğŸŒ™ Night.md
      - Magic/Elements/ğŸŒª Wind.md
      - Magic/Elements/ğŸŒ¿ Nature.md
      - Magic/Elements/ğŸ’§ Water.md
      - Magic/Elements/ğŸ”† Daylight.md
      - Magic/Elements/ğŸ”¥ Flame.md
      - Magic/Elements/ğŸª¨ Earth.md
  - Characters :
    - Samantha :
      - Characters/Samantha/index.md
      - ğŸ“œ Spells :
        - Characters/Samantha/ğŸ“œ Spells/â¯ï¸ Dash.md
        - Characters/Samantha/ğŸ“œ Spells/â±ï¸ Switch Gear.md
        - Characters/Samantha/ğŸ“œ Spells/ğŸ‘‰ Bang.md
        - Characters/Samantha/ğŸ“œ Spells/ğŸ‘Š Jolt.md
        - Characters/Samantha/ğŸ“œ Spells/ğŸ’ª Muscle Manipulation.md
      - History :
        - Characters/Samantha/History/Summary.md
    - Artemis :
      - Characters/Artemis/index.md
      - ğŸ“œ Spells :
        - Characters/Artemis/ğŸ“œ Spells/ğŸ¶ Melody of the Wind.md
    #Other Characters :
      #- Beatrix :
        #- Characters/Other Characters/Beatrix/index.md
        #- ğŸ“œ Spells :
      #- Ashley :
        #- Characters/Other Characters/Ashley/index.md
        #- ğŸ“œ Spells :
    - Template :
      - Characters/Template/index.md
      - ğŸ“œ Spells :
        - Characters/Template/ğŸ“œ Spells/ğŸ“ Spell Blueprint.md
  - World :
    - World/Cresentia.md
    - Society :
      - Stereotypes :
        - World/Society/Stereotypes/âš¡ï¸Lightning Bolt Spell.md
    - Species :
      - World/Species/ğŸ§ Human.md
      - World/Species/ğŸ¦‡ Vampire.md
      - World/Species/ğŸª¦ Undead.md
        
extra:
  generator: false

extra_css: 
    #- stylesheets/extra.css

plugins:
  - search

