site_name: "Adele Magic System" 
site_url: https://adeleprism.github.io/Magic-System
theme:
    name: 'material'
    palette:
      scheme: slate
      primary: deep purple
      accent: blue
    features: 
      - navigation.path
      - navigation.footer
markdown_extensions:
  - toc:
      toc_depth: 0

nav:
  - index.md
  - Magic :
    - Basics of Magic :
      - Magic/Basics of Magic/ğŸ§  Emotions.md
      - Magic/Basics of Magic/ğŸ§™â€â™€ï¸ Affinity.md
      - Magic/Basics of Magic/âœ¨ï¸ Souls of Magic.md
      - Magic/Basics of Magic/ğŸ”£ Links.md
      - Magic/Basics of Magic/ğŸ“œ Spells.md
    - Elements :
      - Magic/Elements/âš¡ï¸ Shock.md
      - Magic/Elements/ğŸŒ™ Night.md
      - Magic/Elements/ğŸŒª Wind.md
      - Magic/Elements/ğŸŒ¿ Nature.md
      - Magic/Elements/ğŸ’§ Water.md
      - Magic/Elements/ğŸ”† Daylight.md
      - Magic/Elements/ğŸ”¥ Flame.md
      - Magic/Elements/ğŸª¨ Earth.md
    - Characters :
      - Samantha :
        - Magic/Characters/Samantha/index.md
        - ğŸ“œ Spells :
          -Magic/Characters/Samantha/Spells/â¯ï¸ Dash.md
          -Magic/Characters/Samantha/Spells/â±ï¸ Switch Gear.md
          -Magic/Characters/Samantha/Spells/ğŸ‘‰ Bang.md
          -Magic/Characters/Samantha/Spells/ğŸ‘Š Jolt.md
          -Magic/Characters/Samantha/Spells/ğŸ’ª Muscle Manipulation.md

extra:
  generator: false

extra_css: 
    #- stylesheets/extra.css

plugins:
  - search

